# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152MspKo6K9nHj5xow5npUosMVmCODqMb
"""

import pandas as pd

# Sample dataset with user activities
data = {
    'user_id': [101, 102, 103, 104, 101],
    'transaction_amount': [500, 3000, 250, 45000, 2000],
    'transaction_location': ['New York', 'London', 'New York', 'Tokyo', 'New York'],
    'transaction_time': ['2024-09-01 10:00:00', '2024-09-01 12:30:00',
                         '2024-09-01 14:45:00', '2024-09-02 09:00:00', '2024-09-02 11:00:00'],
}

# Convert to DataFrame
df = pd.DataFrame(data)
df['transaction_time'] = pd.to_datetime(df['transaction_time'])

# Set thresholds for suspicious activity
amount_threshold = 10000  # Large transaction amount
location_changes_threshold = 2  # Too many location changes
time_threshold_hours = 2  # Too short a time between large transactions

# Detect suspicious activity based on amount
df['suspicious_amount'] = df['transaction_amount'] > amount_threshold

# Detect suspicious activity based on rapid location changes (by user)
df['location_change'] = df.groupby('user_id')['transaction_location'].shift(1) != df['transaction_location']
df['location_changes'] = df.groupby('user_id')['location_change'].cumsum()
df['suspicious_location'] = df['location_changes'] > location_changes_threshold

# Detect suspicious activity based on time differences between large transactions
df['time_diff'] = df.groupby('user_id')['transaction_time'].diff().dt.total_seconds() / 3600  # Convert to hours
df['suspicious_time'] = (df['time_diff'] < time_threshold_hours) & (df['transaction_amount'] > amount_threshold)

# Combine all suspicious activities into one column
df['suspicious_activity'] = df['suspicious_amount'] | df['suspicious_location'] | df['suspicious_time']

# Filter suspicious activities
suspicious_df = df[df['suspicious_activity']]

print("Suspicious Activities Detected:")
print(suspicious_df[['user_id', 'transaction_amount', 'transaction_location', 'transaction_time', 'suspicious_activity']])